// Code generated by goyacc -l yacc.y. DO NOT EDIT.
package cronparser

import __yyfmt__ "fmt"
import "fmt"

func setScannerData(yylex interface{}, data CronResult) {
	yylex.(*Scanner).data = data
}

type yySymType struct {
	yys   int
	empty struct{}
	s     string
	i     int
	c     CronResult
}

const COMMA = 57346
const COLON = 57347
const ASTERISK = 57348
const SLASH = 57349
const DASH = 57350
const STRING = 57351
const NUMBER = 57352

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"COMMA",
	"COLON",
	"ASTERISK",
	"SLASH",
	"DASH",
	"STRING",
	"NUMBER",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

var yyExca = [...]int{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 67

var yyAct = [...]int{
	31, 21, 12, 6, 33, 45, 34, 3, 32, 36,
	35, 39, 29, 19, 11, 17, 18, 27, 28, 20,
	15, 1, 2, 30, 16, 37, 38, 14, 0, 15,
	0, 13, 40, 16, 43, 44, 34, 0, 0, 36,
	35, 46, 47, 48, 9, 23, 49, 24, 10, 22,
	26, 25, 8, 0, 9, 4, 7, 24, 10, 5,
	26, 25, 42, 0, 0, 0, 41,
}

var yyPact = [...]int{
	49, -1000, -1000, 48, 7, -1000, 23, 49, 49, 6,
	-1000, 49, 41, 38, 38, 5, -1000, -1000, -1000, 38,
	-1000, 0, 14, 14, 4, -1000, -1000, -1000, -1000, 14,
	-1000, 58, 51, 51, -2, -1000, -1000, -1000, -1000, 51,
	-1000, 30, 30, -1000, -1000, 30, -1000, -1000, -1000, -1000,
}

var yyPgo = [...]int{
	0, 7, 3, 2, 1, 0, 22, 21,
}

var yyR1 = [...]int{
	0, 7, 6, 1, 1, 1, 1, 1, 2, 2,
	2, 2, 2, 3, 3, 3, 3, 3, 4, 4,
	4, 4, 4, 4, 5, 5, 5, 5, 5, 5,
}

var yyR2 = [...]int{
	0, 1, 5, 1, 3, 3, 3, 1, 1, 3,
	3, 3, 1, 1, 3, 3, 3, 1, 1, 3,
	3, 3, 1, 1, 1, 3, 3, 3, 1, 1,
}

var yyChk = [...]int{
	-1000, -7, -6, -1, 6, 10, -2, 8, 4, 6,
	10, 7, -3, 8, 4, 6, 10, -1, -1, 7,
	-1, -4, 8, 4, 6, 10, 9, -2, -2, 7,
	-2, -5, 8, 4, 6, 10, 9, -3, -3, 7,
	-3, 8, 4, -4, -4, 7, -4, -5, -5, -5,
}

var yyDef = [...]int{
	0, -2, 1, 0, 3, 7, 0, 0, 0, 8,
	12, 0, 0, 0, 0, 13, 17, 5, 6, 0,
	4, 0, 0, 0, 18, 22, 23, 10, 11, 0,
	9, 2, 0, 0, 24, 28, 29, 15, 16, 0,
	14, 0, 0, 20, 21, 0, 19, 26, 27, 25,
}

var yyTok1 = [...]int{
	1,
}

var yyTok2 = [...]int{
	2, 3, 4, 5, 6, 7, 8, 9, 10,
}

var yyTok3 = [...]int{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := yyPact[state]
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && yyChk[yyAct[n]] == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || yyExca[i+1] != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := yyExca[i]
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = yyTok1[0]
		goto out
	}
	if char < len(yyTok1) {
		token = yyTok1[char]
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = yyTok2[char-yyPrivate]
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = yyTok3[i+0]
		if token == char {
			token = yyTok3[i+1]
			goto out
		}
	}

out:
	if token == 0 {
		token = yyTok2[1] /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = yyPact[yystate]
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = yyAct[yyn]
	if yyChk[yyn] == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = yyDef[yystate]
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && yyExca[xi+1] == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = yyExca[xi+0]
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = yyExca[xi+1]
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = yyPact[yyS[yyp].yys] + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = yyAct[yyn] /* simulate a shift of "error" */
					if yyChk[yystate] == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= yyR2[yyn]
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = yyR1[yyn]
	yyg := yyPgo[yyn]
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = yyAct[yyg]
	} else {
		yystate = yyAct[yyj]
		if yyChk[yystate] != -yyn {
			yystate = yyAct[yyg]
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			setScannerData(yylex, yyDollar[1].c)
		}
	case 2:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			yyVAL.c = CronResult{Minutes: yyDollar[1].s, Hours: yyDollar[2].s, Days: yyDollar[3].s, Months: yyDollar[4].s, Weeks: yyDollar[5].s}
		}
	case 3:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.s = "*"
		}
	case 4:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.s = fmt.Sprintf("*/%s", yyDollar[3].s)
		}
	case 5:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.s = fmt.Sprintf("%s-%s", yyDollar[1].s, yyDollar[3].s)
		}
	case 6:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.s = fmt.Sprintf("%s,%s", yyDollar[1].s, yyDollar[3].s)
		}
	case 7:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			if !isNumValid(yyDollar[1].i, 0, 59) {
				yylex.Error(fmt.Sprintf("minutes:%d should between 0-59", yyDollar[1].i))
			}
			yyVAL.s = fmt.Sprintf("%d", yyDollar[1].i)
		}
	case 8:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.s = "*"
		}
	case 9:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.s = fmt.Sprintf("*/%s", yyDollar[3].s)
		}
	case 10:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.s = fmt.Sprintf("%s-%s", yyDollar[1].s, yyDollar[3].s)
		}
	case 11:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.s = fmt.Sprintf("%s,%s", yyDollar[1].s, yyDollar[3].s)
		}
	case 12:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			if !isNumValid(yyDollar[1].i, 0, 23) {
				yylex.Error(fmt.Sprintf("hours:%d should between 0-23", yyDollar[1].i))
			}
			yyVAL.s = fmt.Sprintf("%d", yyDollar[1].i)
		}
	case 13:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.s = "*"
		}
	case 14:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.s = fmt.Sprintf("*/%s", yyDollar[3].s)
		}
	case 15:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.s = fmt.Sprintf("%s-%s", yyDollar[1].s, yyDollar[3].s)
		}
	case 16:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.s = fmt.Sprintf("%s,%s", yyDollar[1].s, yyDollar[3].s)
		}
	case 17:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			if !isNumValid(yyDollar[1].i, 1, 31) {
				yylex.Error(fmt.Sprintf("days:%d should between 1-31", yyDollar[1].i))
			}
			yyVAL.s = fmt.Sprintf("%d", yyDollar[1].i)
		}
	case 18:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.s = "*"
		}
	case 19:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.s = fmt.Sprintf("*/%s", yyDollar[3].s)
		}
	case 20:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.s = fmt.Sprintf("%s-%s", yyDollar[1].s, yyDollar[3].s)
		}
	case 21:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.s = fmt.Sprintf("%s,%s", yyDollar[1].s, yyDollar[3].s)
		}
	case 22:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			if !isMonthValid(yyDollar[1].i) {
				yylex.Error(fmt.Sprintf("months:%d should between 1–12 or JAN–DEC", yyDollar[1].i))
			}
			yyVAL.s = fmt.Sprintf("%d", yyDollar[1].i)
		}
	case 23:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			if !isMonthValid(yyDollar[1].s) {
				yylex.Error(fmt.Sprintf("months:%s should between 1–12 or JAN–DEC", yyDollar[1].s))
			}
			yyVAL.s = fmt.Sprintf("%s", yyDollar[1].s)
		}
	case 24:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.s = "*"
		}
	case 25:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.s = fmt.Sprintf("*/%s", yyDollar[3].s)
		}
	case 26:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.s = fmt.Sprintf("%s-%s", yyDollar[1].s, yyDollar[3].s)
		}
	case 27:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.s = fmt.Sprintf("%s,%s", yyDollar[1].s, yyDollar[3].s)
		}
	case 28:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			if !isWeekValid(yyDollar[1].i) {
				yylex.Error(fmt.Sprintf("weeks:%d should between 0–6 or SUN–SAT", yyDollar[1].i))
			}
			yyVAL.s = fmt.Sprintf("%d", yyDollar[1].i)
		}
	case 29:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			if !isWeekValid(yyDollar[1].s) {
				yylex.Error(fmt.Sprintf("months:%s should between 0-6 or SUN–SAT", yyDollar[1].s))
			}
			yyVAL.s = fmt.Sprintf("%s", yyDollar[1].s)
		}
	}
	goto yystack /* stack new state and value */
}
